<?php

/**
* This is the model base class for the table "msg".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "Msg".
*
* Columns in table "msg" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property integer $uid
* @property string $data
* @property string $type
* @property integer $snd_type
* @property integer $snd_status
* @property integer $priority
* @property integer $to_id
* @property string $msg_pid
* @property integer $create_time
* @property integer $sent_time
* @property integer $delete_time
*
*/
abstract class BaseMsg extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'msg';
}

public static function representingColumn() {
return 'data';
}

public function rules() {
return array(
array('uid, data, create_time', 'required'),
array('uid, snd_type, snd_status, priority, to_id, create_time, sent_time, delete_time', 'numerical', 'integerOnly'=>true),
array('type', 'length', 'max'=>50),
array('msg_pid', 'length', 'max'=>20),
array('type, snd_type, snd_status, priority, to_id, msg_pid, sent_time, delete_time', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, uid, data, type, snd_type, snd_status, priority, to_id, msg_pid, create_time, sent_time, delete_time', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('msg', 'id'),
'uid' => Yii::t('msg', 'uid'),
'data' => Yii::t('msg', 'data'),
'type' => Yii::t('msg', 'type'),
'snd_type' => Yii::t('msg', 'snd_type'),
'snd_status' => Yii::t('msg', 'snd_status'),
'priority' => Yii::t('msg', 'priority'),
'to_id' => Yii::t('msg', 'to_id'),
'msg_pid' => Yii::t('msg', 'msg_pid'),
'create_time' => Yii::t('msg', 'create_time'),
'sent_time' => Yii::t('msg', 'sent_time'),
'delete_time' => Yii::t('msg', 'delete_time'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('uid', $this->uid);
$criteria->compare('data', $this->data, true);
$criteria->compare('type', $this->type, true);
$criteria->compare('snd_type', $this->snd_type);
$criteria->compare('snd_status', $this->snd_status);
$criteria->compare('priority', $this->priority);
$criteria->compare('to_id', $this->to_id);
$criteria->compare('msg_pid', $this->msg_pid, true);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('sent_time', $this->sent_time);
$criteria->compare('delete_time', $this->delete_time);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}