<?php

/**
* This is the model base class for the table "notice_post".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "NoticePost".
*
* Columns in table "notice_post" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property integer $cate_id
* @property string $title
* @property string $content
* @property integer $create_time
* @property integer $creator_id
*
*/
abstract class BaseNoticePost extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'notice_post';
}

public static function representingColumn() {
return 'title';
}

public function rules() {
return array(
array('cate_id, title, content', 'required'),
array('cate_id, create_time, creator_id', 'numerical', 'integerOnly'=>true),
array('title', 'length', 'max'=>120),
array('creator_id', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, cate_id, title, content, create_time, creator_id', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('notice_post', 'id'),
'cate_id' => Yii::t('notice_post', 'cate_id'),
'title' => Yii::t('notice_post', 'title'),
'content' => Yii::t('notice_post', 'content'),
'create_time' => Yii::t('notice_post', 'create_time'),
'creator_id' => Yii::t('notice_post', 'creator_id'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('cate_id', $this->cate_id);
$criteria->compare('title', $this->title, true);
$criteria->compare('content', $this->content, true);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('creator_id', $this->creator_id);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}