<?php

/**
 * This is the model base class for the table "status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "status" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $update
 * @property integer $type
 * @property integer $creator
 * @property string $created
 * @property integer $profile
 * @property integer $approved
 *
 */
abstract class BaseStatus extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'status';
    }

    public static function representingColumn()
    {
        return 'update';
    }

    public function rules()
    {
        return array(
            array('update, type, creator,  profile', 'required'),
            array('type, creator, profile, approved', 'numerical', 'integerOnly' => true),
            array('approved', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, update, type, creator, created, profile, approved', 'safe', 'on' => 'search'),
        );
    }



    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('status', 'id'),
            'update' => Yii::t('status', 'update'),
            'type' => Yii::t('status', 'type'),
            'creator' => Yii::t('status', 'creator'),
            'created' => Yii::t('status', 'created'),
            'profile' => Yii::t('status', 'profile'),
            'approved' => Yii::t('status', 'approved'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('update', $this->update, true);
        $criteria->compare('type', $this->type);
        $criteria->compare('creator', $this->creator);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('profile', $this->profile);
        $criteria->compare('approved', $this->approved);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}