<?php

/**
* This is the model base class for the table "news_entry".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "NewsEntry".
*
* Columns in table "news_entry" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property integer $creator
* @property integer $create_time
* @property integer $cate_id
* @property string $title
*
*/
abstract class BaseNewsEntry extends GxActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'news_entry';
}

public static function representingColumn() {
return 'title';
}

public function rules() {
return array(
array(' title', 'required'),
array('creator, create_time, cate_id', 'numerical', 'integerOnly'=>true),
array('id', 'length', 'max'=>10),
array('title', 'length', 'max'=>255),
array('id, creator, cate_id', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, creator, create_time, cate_id, title', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('news_entry', 'id'),
'creator' => Yii::t('news_entry', 'creator'),
'create_time' => Yii::t('news_entry', 'create_time'),
'cate_id' => Yii::t('news_entry', 'cate_id'),
'title' => Yii::t('news_entry', 'title'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('creator', $this->creator);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('cate_id', $this->cate_id);
$criteria->compare('title', $this->title, true);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}