<?php

/**
* This is the model base class for the table "sys_hook".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "SysHook".
*
* Columns in table "sys_hook" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property string $host_module
* @property string $hook_name
* @property string $client_module
* @property string $client_hook_name
* @property string $hook_content
* @property integer $priority
* @property string $type
* @property integer $create_time
*
*/
abstract class BaseSysHook extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'sys_hook';
}

public static function representingColumn() {
return 'host_module';
}

public function rules() {

return array(
array('hook_name, client_hook_name, hook_content, create_time', 'required'),
array('priority, create_time', 'numerical', 'integerOnly'=>true),
array('host_module, client_module', 'length', 'max'=>80),
array('hook_name, client_hook_name', 'length', 'max'=>255),
array('type', 'length', 'max'=>25),
array('host_module, client_module, priority, type', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, host_module, hook_name, client_module, client_hook_name, hook_content, priority, type, create_time', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('sys_hook', 'id'),
'host_module' => Yii::t('sys_hook', 'host_module'),
'hook_name' => Yii::t('sys_hook', 'hook_name'),
'client_module' => Yii::t('sys_hook', 'client_module'),
'client_hook_name' => Yii::t('sys_hook', 'client_hook_name'),
'hook_content' => Yii::t('sys_hook', 'hook_content'),
'priority' => Yii::t('sys_hook', 'priority'),
'type' => Yii::t('sys_hook', 'type'),
'create_time' => Yii::t('sys_hook', 'create_time'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('host_module', $this->host_module, true);
$criteria->compare('hook_name', $this->hook_name, true);
$criteria->compare('client_module', $this->client_module, true);
$criteria->compare('client_hook_name', $this->client_hook_name, true);
$criteria->compare('hook_content', $this->hook_content, true);
$criteria->compare('priority', $this->priority);
$criteria->compare('type', $this->type, true);
$criteria->compare('create_time', $this->create_time);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}