<?php

/**
* This is the model base class for the table "sys_object_thumb_vote".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "SysObjectThumbVote".
*
* Columns in table "sys_object_thumb_vote" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property string $object_name
* @property string $table_track
* @property string $row_prefix
* @property integer $duplicate_sec
* @property string $trigger_table
* @property string $trigger_field_up_vote
* @property string $trigger_field_down_vote
* @property string $trigger_field_id
* @property integer $is_on
*
*/
abstract class BaseSysObjectThumbVote extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'sys_object_thumb_vote';
}

public static function representingColumn() {
return 'object_name';
}

public function rules() {
return array(
array('object_name, table_track, trigger_table', 'required'),
array('duplicate_sec, is_on', 'numerical', 'integerOnly'=>true),
array('object_name, table_track', 'length', 'max'=>50),
array('row_prefix', 'length', 'max'=>20),
array('trigger_table, trigger_field_up_vote, trigger_field_down_vote, trigger_field_id', 'length', 'max'=>60),
array('row_prefix, duplicate_sec, trigger_field_up_vote, trigger_field_down_vote, trigger_field_id, is_on', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, object_name, table_track, row_prefix, duplicate_sec, trigger_table, trigger_field_up_vote, trigger_field_down_vote, trigger_field_id, is_on', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('sys_object_thumb_vote', 'id'),
'object_name' => Yii::t('sys_object_thumb_vote', 'object_name'),
'table_track' => Yii::t('sys_object_thumb_vote', 'table_track'),
'row_prefix' => Yii::t('sys_object_thumb_vote', 'row_prefix'),
'duplicate_sec' => Yii::t('sys_object_thumb_vote', 'duplicate_sec'),
'trigger_table' => Yii::t('sys_object_thumb_vote', 'trigger_table'),
'trigger_field_up_vote' => Yii::t('sys_object_thumb_vote', 'trigger_field_up_vote'),
'trigger_field_down_vote' => Yii::t('sys_object_thumb_vote', 'trigger_field_down_vote'),
'trigger_field_id' => Yii::t('sys_object_thumb_vote', 'trigger_field_id'),
'is_on' => Yii::t('sys_object_thumb_vote', 'is_on'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('object_name', $this->object_name, true);
$criteria->compare('table_track', $this->table_track, true);
$criteria->compare('row_prefix', $this->row_prefix, true);
$criteria->compare('duplicate_sec', $this->duplicate_sec);
$criteria->compare('trigger_table', $this->trigger_table, true);
$criteria->compare('trigger_field_up_vote', $this->trigger_field_up_vote, true);
$criteria->compare('trigger_field_down_vote', $this->trigger_field_down_vote, true);
$criteria->compare('trigger_field_id', $this->trigger_field_id, true);
$criteria->compare('is_on', $this->is_on);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}