<?php

/**
* This is the model base class for the table "sys_album_object".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "SysAlbumObject".
*
* Columns in table "sys_album_object" available as properties of the model,
* and there are no model relations.
*
* @property integer $id_album
* @property integer $id_object
* @property integer $obj_order
*
*/
abstract class BaseSysAlbumObject extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'sys_album_object';
}

public static function representingColumn() {
return array(
    'id_album',
        'id_object',
    );
}

public function rules() {
return array(
array('id_album, id_object', 'required'),
array('id_album, id_object, obj_order', 'numerical', 'integerOnly'=>true),
array('obj_order', 'default', 'setOnEmpty' => true, 'value' => null),
array('id_album, id_object, obj_order', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id_album' => Yii::t('sys_album_object', 'id_album'),
'id_object' => Yii::t('sys_album_object', 'id_object'),
'obj_order' => Yii::t('sys_album_object', 'obj_order'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id_album', $this->id_album);
$criteria->compare('id_object', $this->id_object);
$criteria->compare('obj_order', $this->obj_order);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}