<?php

/**
* This is the model base class for the table "tbl_comments".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "Comment".
*
* Columns in table "tbl_comments" available as properties of the model,
* and there are no model relations.
*
* @property string $object_name
* @property integer $object_id
* @property integer $cmt_id
* @property integer $cmt_parent_id
* @property integer $author_id
* @property string $user_name
* @property string $user_email
* @property string $cmt_text
* @property integer $create_time
* @property integer $update_time
* @property integer $status
* @property integer $replies
* @property integer $mood
*
*/
abstract class BaseComment extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'tbl_comments';
}

public static function representingColumn() {
return 'object_name';
}

public function rules() {
return array(
array('object_name, object_id', 'required'),
array('object_id, cmt_parent_id, author_id, create_time, update_time, status, replies, mood', 'numerical', 'integerOnly'=>true),
array('object_name', 'length', 'max'=>50),
array('user_name, user_email', 'length', 'max'=>128),
array('cmt_text', 'safe'),
array('cmt_parent_id, author_id, user_name, user_email, cmt_text, create_time, update_time, status, replies, mood', 'default', 'setOnEmpty' => true, 'value' => null),
array('object_name, object_id, cmt_id, cmt_parent_id, author_id, user_name, user_email, cmt_text, create_time, update_time, status, replies, mood', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'object_name' => Yii::t('tbl_comments', 'object_name'),
'object_id' => Yii::t('tbl_comments', 'object_id'),
'cmt_id' => Yii::t('tbl_comments', 'cmt_id'),
'cmt_parent_id' => Yii::t('tbl_comments', 'cmt_parent_id'),
'author_id' => Yii::t('tbl_comments', 'author_id'),
'user_name' => Yii::t('tbl_comments', 'user_name'),
'user_email' => Yii::t('tbl_comments', 'user_email'),
'cmt_text' => Yii::t('tbl_comments', 'cmt_text'),
'create_time' => Yii::t('tbl_comments', 'create_time'),
'update_time' => Yii::t('tbl_comments', 'update_time'),
'status' => Yii::t('tbl_comments', 'status'),
'replies' => Yii::t('tbl_comments', 'replies'),
'mood' => Yii::t('tbl_comments', 'mood'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('object_name', $this->object_name, true);
$criteria->compare('object_id', $this->object_id);
$criteria->compare('cmt_id', $this->cmt_id);
$criteria->compare('cmt_parent_id', $this->cmt_parent_id);
$criteria->compare('author_id', $this->author_id);
$criteria->compare('user_name', $this->user_name, true);
$criteria->compare('user_email', $this->user_email, true);
$criteria->compare('cmt_text', $this->cmt_text, true);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('update_time', $this->update_time);
$criteria->compare('status', $this->status);
$criteria->compare('replies', $this->replies);
$criteria->compare('mood', $this->mood);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}