<?php

/**
* This is the model base class for the table "sys_object_vote".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "SysObjectVote".
*
* Columns in table "sys_object_vote" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property string $object_name
* @property string $table_rating
* @property string $table_track
* @property string $row_prefix
* @property integer $max_votes
* @property integer $duplicate_sec
* @property string $trigger_table
* @property string $trigger_field_rate
* @property string $trigger_field_rate_count
* @property string $trigger_field_id
* @property string $override_class
* @property string $post_name
* @property integer $is_on
*
*/
abstract class BaseSysObjectVote extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'sys_object_vote';
}

public static function representingColumn() {
return 'object_name';
}

public function rules() {
return array(
array('object_name, table_rating, table_track, row_prefix, max_votes, duplicate_sec, trigger_table, trigger_field_rate, trigger_field_rate_count, trigger_field_id', 'required'),
array('max_votes, duplicate_sec, is_on', 'numerical', 'integerOnly'=>true),
array('object_name, table_rating, table_track, post_name', 'length', 'max'=>50),
array('row_prefix', 'length', 'max'=>20),
array('trigger_table, trigger_field_rate, trigger_field_rate_count, trigger_field_id', 'length', 'max'=>60),
array('override_class', 'length', 'max'=>256),
array('override_class, post_name, is_on', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, object_name, table_rating, table_track, row_prefix, max_votes, duplicate_sec, trigger_table, trigger_field_rate, trigger_field_rate_count, trigger_field_id, override_class, post_name, is_on', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('sys_object_vote', 'id'),
'object_name' => Yii::t('sys_object_vote', 'object_name'),
'table_rating' => Yii::t('sys_object_vote', 'table_rating'),
'table_track' => Yii::t('sys_object_vote', 'table_track'),
'row_prefix' => Yii::t('sys_object_vote', 'row_prefix'),
'max_votes' => Yii::t('sys_object_vote', 'max_votes'),
'duplicate_sec' => Yii::t('sys_object_vote', 'duplicate_sec'),
'trigger_table' => Yii::t('sys_object_vote', 'trigger_table'),
'trigger_field_rate' => Yii::t('sys_object_vote', 'trigger_field_rate'),
'trigger_field_rate_count' => Yii::t('sys_object_vote', 'trigger_field_rate_count'),
'trigger_field_id' => Yii::t('sys_object_vote', 'trigger_field_id'),
'override_class' => Yii::t('sys_object_vote', 'override_class'),
'post_name' => Yii::t('sys_object_vote', 'post_name'),
'is_on' => Yii::t('sys_object_vote', 'is_on'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('object_name', $this->object_name, true);
$criteria->compare('table_rating', $this->table_rating, true);
$criteria->compare('table_track', $this->table_track, true);
$criteria->compare('row_prefix', $this->row_prefix, true);
$criteria->compare('max_votes', $this->max_votes);
$criteria->compare('duplicate_sec', $this->duplicate_sec);
$criteria->compare('trigger_table', $this->trigger_table, true);
$criteria->compare('trigger_field_rate', $this->trigger_field_rate, true);
$criteria->compare('trigger_field_rate_count', $this->trigger_field_rate_count, true);
$criteria->compare('trigger_field_id', $this->trigger_field_id, true);
$criteria->compare('override_class', $this->override_class, true);
$criteria->compare('post_name', $this->post_name, true);
$criteria->compare('is_on', $this->is_on);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}