<?php

/**
* This is the model base class for the table "sys_album".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "SysAlbum".
*
* Columns in table "sys_album" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property string $caption
* @property string $cover_uri
* @property string $location
* @property string $description
* @property string $type
* @property integer $uid
* @property string $status
* @property integer $create_time
* @property integer $obj_count
* @property integer $last_obj_id
* @property integer $allow_view
*
*/
abstract class BaseSysAlbum extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'sys_album';
}

public static function representingColumn() {
return 'caption';
}

public function rules() {
return array(
array('caption', 'required'),
array('uid, create_time, obj_count, last_obj_id, allow_view', 'numerical', 'integerOnly'=>true),
array('caption, location', 'length', 'max'=>128),
array('cover_uri, description', 'length', 'max'=>255),
array('type', 'length', 'max'=>20),
array('status', 'length', 'max'=>7),
array('cover_uri, location, description, type, uid, status, create_time, obj_count, last_obj_id, allow_view', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, caption, cover_uri, location, description, type, uid, status, create_time, obj_count, last_obj_id, allow_view', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('sys_album', 'id'),
'caption' => Yii::t('sys_album', 'caption'),
'cover_uri' => Yii::t('sys_album', 'cover_uri'),
'location' => Yii::t('sys_album', 'location'),
'description' => Yii::t('sys_album', 'description'),
'type' => Yii::t('sys_album', 'type'),
'uid' => Yii::t('sys_album', 'uid'),
'status' => Yii::t('sys_album', 'status'),
'create_time' => Yii::t('sys_album', 'create_time'),
'obj_count' => Yii::t('sys_album', 'obj_count'),
'last_obj_id' => Yii::t('sys_album', 'last_obj_id'),
'allow_view' => Yii::t('sys_album', 'allow_view'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('caption', $this->caption, true);
$criteria->compare('cover_uri', $this->cover_uri, true);
$criteria->compare('location', $this->location, true);
$criteria->compare('description', $this->description, true);
$criteria->compare('type', $this->type, true);
$criteria->compare('uid', $this->uid);
$criteria->compare('status', $this->status, true);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('obj_count', $this->obj_count);
$criteria->compare('last_obj_id', $this->last_obj_id);
$criteria->compare('allow_view', $this->allow_view);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}