<?php

/**
* This is the model base class for the table "yiisession".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "Yiisession".
*
* Columns in table "yiisession" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property integer $expire
* @property string $data
* @property integer $user_id
*
*/
abstract class BaseYiisession extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'yiisession';
}

public static function representingColumn() {
return 'id';
}

public function rules() {
return array(
array('id', 'required'),
array('expire, user_id', 'numerical', 'integerOnly'=>true),
array('id', 'length', 'max'=>32),
array('data', 'safe'),
array('expire, data, user_id', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, expire, data, user_id', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('yiisession', 'id'),
'expire' => Yii::t('yiisession', 'expire'),
'data' => Yii::t('yiisession', 'data'),
'user_id' => Yii::t('yiisession', 'user_id'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('expire', $this->expire);
$criteria->compare('data', $this->data, true);
$criteria->compare('user_id', $this->user_id);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}