<?php

return array(
    //code  =>  'mage name      Width   Height  Alt
    '>:)'   =>  array('19.gif', '18',   '18',   'devil'),
    ':))'   =>  array('21.gif', '18',   '18',   'laughing'),
    ':)'    =>  array('1.gif',  '18',   '18',   'happy'),
    ':(('   =>  array('20.gif', '22',   '18',   'crying'),
    ':('    =>  array('2.gif',  '18',   '18',   'sad'),
    ';)'    =>  array('3.gif',  '18',   '18',   'winking'),
    '>:D<'  =>  array('6.gif',  '42',   '18',   'big hug'),
    ':D'    =>  array('4.gif',  '18',   '18',   'big grin'),
    ';;)'   =>  array('5.gif',  '18',   '18',   'batting eyelashes'),
    ':-/'   =>  array('7.gif',  '20',   '18',   'confused'),
    ':x'    =>  array('8.gif',  '18',   '18',   'love struck'),
    ':">'   =>  array('9.gif',  '18',   '18',   'blushing'),
    ':P'    =>  array('10.gif', '18',   '18',   'tongue'),
    ':*'    =>  array('11.gif', '18',   '18',   'kiss'),
    '=(('   =>  array('12.gif', '18',   '18',   'broken heart'),
    ':o'    =>  array('13.gif', '18',   '18',   'surprise'),
    'X('    =>  array('14.gif', '34',   '18',   'angry'),
    ':>'    =>  array('15.gif', '18',   '18',   'smug'),
    'B-)'   =>  array('16.gif', '18',   '18',   'cool'),
    ':-S'   =>  array('17.gif', '18',   '18',   'worried'),
    '#:-S'  =>  array('18.gif', '34',   '18',   'whew!'),
    ':|'    =>  array('22.gif',  '18',   '18',   'straight face'),
    '/:)'   =>  array('23.gif',  '18',   '18',   'raised eyebrows'),
    '=))'   =>  array('24.gif',  '30',   '18',   'rolling on the floor'),
    'O:-)'  =>  array('25.gif',  '30',   '18',   'angel'),
    ':-B'   =>  array('26.gif',  '24',   '18',   'nerd'),
    '=;'    =>  array('27.gif',  '18',   '18',   'talk to the hand'),
    ':-c'   =>  array('101.gif', '28',   '18',   'call me'),
    ':)]'   =>  array('100.gif', '31',   '18',   'on the phone'),
    '~X('   =>  array('102.gif', '44',   '18',   'at wits\' end'),
    ':-h'   =>  array('103.gif', '28',   '18',   'wave'),
    ':-t'   =>  array('104.gif', '30',   '18',   'time out'),
    '8->'   =>  array('105.gif', '23',   '18',   'day dreaming'),
    'I-)'   =>  array('28.gif',  '21',   '18',   'sleepy'),
    '8-|'   =>  array('29.gif',  '18',   '18',   'rolling eyes'),
    'L-)'   =>  array('30.gif',  '24',   '18',   'loser'),
    ':-&'   =>  array('31.gif',  '18',   '18',   'sick'),
    ':-$'   =>  array('32.gif',  '18',   '18',   'don\'t tell anyone'),
    '[-('   =>  array('33.gif',  '18',   '18',   'no talking'),
    ':O)'   =>  array('34.gif',  '18',   '18',   'clown'),
    '8-}'   =>  array('35.gif',  '24',   '18',   'silly'),
    '<:-P'  =>  array('36.gif',  '38',   '18',   'party'),
    '(:|'   =>  array('37.gif',  '18',   '18',   'yawn'),
    '=P~'   =>  array('38.gif',  '18',   '18',   'drooling'),
    ':-?'   =>  array('39.gif',  '18',   '18',   'thinking'),
    '#-o'   =>  array('40.gif',  '24',   '18',   'd\'oh'),
    '=D>'   =>  array('41.gif',  '18',   '18',   'applause'),
    ':-SS'  =>  array('42.gif',  '36',   '18',   'nail biting'),
    '@-)'   =>  array('43.gif',  '18',   '18',   'hypnotized'),
    ':^o'   =>  array('44.gif',  '18',   '18',   'liar'),
    ':-w'   =>  array('45.gif',  '23',   '18',   'waiting'),
    ':-<'   =>  array('46.gif',  '24',   '18',   'sigh'),
    '>:P'   =>  array('47.gif',  '18',   '18',   'phbbbbt'),
    '<):)'  =>  array('48.gif',  '18',   '18',   'cowboy'),
    'X_X'   =>  array('109.gif',  '25',   '18',   'I don\'t want to see'),
    ':!!'   =>  array('110.gif',  '36',   '18',   'hurry up!'),
    '\m/'   =>  array('111.gif',  '32',   '18',   'rock on!'),
    ':-q'   =>  array('112.gif',  '28',   '18',   'thumbs down'),
    ':-bd'  =>  array('113.gif',  '39',   '18',   'thumbs up'),
    '^#(^'  =>  array('114.gif',  '40',   '18',   'it wasn\'t me'),
    ':ar!'  =>  array('pirate_2.gif',  '20',   '20',   'pirate'),
    ':-??'  =>  array('106.gif',  '40',   '18',   'I don\'t know'),
    '%-('   =>  array('107.gif',  '52',   '18',   'not listening'),
    '[-O<'  =>  array('63.gif',  '18',   '18',   'praying'),
    ':-L'   =>  array('62.gif',  '18',   '18',   'frustrated'),
    '$-)'   =>  array('64.gif',  '18',   '18',   'money eyes'),
    ':-"'   =>  array('65.gif',  '22',   '18',   'whistling'),
    'b-('   =>  array('66.gif',  '18',   '18',   'feeling beat up'),
    ':)>-'  =>  array('67.gif',  '22',   '18',   'peace sign'),
    '[-X'   =>  array('68.gif',  '22',   '18',   'shame on you'),
    '\:D/'  =>  array('69.gif',  '26',   '18',   'dancing'),
    '>:/'   =>  array('70.gif',  '23',   '18',   'bring it on'),
    ';))'   =>  array('71.gif',  '18',   '18',   'hee hee'),
    ':-@'   =>  array('76.gif',  '36',   '18',   'chatterbox'),
    '^:)^'  =>  array('77.gif',  '32',   '18',   'not worthy'),
    ':-j'   =>  array('78.gif',  '26',   '18',   'oh go on'),
);