<?php

/**
 * This is the model base class for the table "admin_role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminRole".
 *
 * Columns in table "admin_role" available as properties of the model,
 * followed by relations of table "admin_role" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property integer $disabled
 * @property string $create_time
 * @property string $update_time
 *
 * @property FlyAdminMenu[] $flyAdminMenus
 */
abstract class BaseAdminRole extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'admin_role';
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('name,purviews', 'required'),
            array('disabled', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 50),
            array('create_time, update_time', 'length', 'max' => 10),
            array('description', 'safe'),
            array('description, disabled', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, description, disabled, create_time, update_time', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'flyAdminMenus' => array(self::MANY_MANY, 'FlyAdminMenu', 'admin_role_priv(role_id, menu_id)'),
        );
    }

    public function pivotModels()
    {
        return array(
            'flyAdminMenus' => 'AdminRolePriv',
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('admin_role', 'id'),
            'name' => Yii::t('admin_role', 'name'),
            'description' => Yii::t('admin_role', 'description'),
            'disabled' => Yii::t('admin_role', 'disabled'),
            'create_time' => Yii::t('admin_role', 'create_time'),
            'update_time' => Yii::t('admin_role', 'update_time'),
            'flyAdminMenus' => Yii::t('admin_role', 'flyAdminMenus'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('disabled', $this->disabled);
        $criteria->compare('create_time', $this->create_time, true);
        $criteria->compare('update_time', $this->update_time, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}