<?php

/**
 * This is the model base class for the table "admin_menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminMenu".
 *
 * Columns in table "admin_menu" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $root
 * @property string $lft
 * @property string $rgt
 * @property integer $level
 * @property string $label
 * @property string $url
 * @property string $params
 * @property string $ajaxoptions
 * @property string $htmloptions
 * @property integer $is_visible
 * @property integer $uid
 * @property string $group_code
 *
 */
abstract class BaseAdminMenu extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'admin_menu';
    }

    public static function representingColumn()
    {
        return 'label';
    }

    public function rules()
    {
        return array(
            array('label', 'required'),
            array('level, is_visible, uid', 'numerical', 'integerOnly' => true),
            array('label, url', 'length', 'max' => 255),
            array('group_code', 'length', 'max' => 25),
            array('params, ajaxoptions, htmloptions', 'safe'),
            array('root, url, params, ajaxoptions, htmloptions, is_visible, uid, group_code', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, root, lft, rgt, level, label, url, params, ajaxoptions, htmloptions, is_visible, uid, group_code', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('admin_menu', 'id'),
            'root' => Yii::t('admin_menu', 'root'),
            'lft' => Yii::t('admin_menu', 'lft'),
            'rgt' => Yii::t('admin_menu', 'rgt'),
            'level' => Yii::t('admin_menu', 'level'),
            'label' => Yii::t('admin_menu', 'label'),
            'url' => Yii::t('admin_menu', 'url'),
            'params' => Yii::t('admin_menu', 'params'),
            'ajaxoptions' => Yii::t('admin_menu', 'ajaxoptions'),
            'htmloptions' => Yii::t('admin_menu', 'htmloptions'),
            'is_visible' => Yii::t('admin_menu', 'is_visible'),
            'uid' => Yii::t('admin_menu', 'uid'),
            'group_code' => Yii::t('admin_menu', 'group_code'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('root', $this->root, true);
        $criteria->compare('lft', $this->lft, true);
        $criteria->compare('rgt', $this->rgt, true);
        $criteria->compare('level', $this->level);
        $criteria->compare('label', $this->label, true);
        $criteria->compare('url', $this->url, true);
        $criteria->compare('params', $this->params, true);
        $criteria->compare('ajaxoptions', $this->ajaxoptions, true);
        $criteria->compare('htmloptions', $this->htmloptions, true);
        $criteria->compare('is_visible', $this->is_visible);
        $criteria->compare('uid', $this->uid);
        $criteria->compare('group_code', $this->group_code, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}