<?php

/**
 * This is the model base class for the table "admin_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminUser".
 *
 * Columns in table "admin_user" available as properties of the model,
 * followed by relations of table "admin_user" available as properties of the model.
 *
 * @property string $id
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $encrypt
 * @property string $role_id
 * @property integer $disabled
 * @property string $setting
 * @property string $create_time
 * @property string $update_time
 *
 * @property AdminRole $role
 */
abstract class BaseAdminUser extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'admin_user';
    }

    public static function representingColumn()
    {
        return 'username';
    }




    public function relations()
    {
        return array(
            'role' => array(self::BELONGS_TO, 'AdminRole', 'role_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('admin_user', 'id'),
            'username' => Yii::t('admin_user', 'username'),
            'password' => Yii::t('admin_user', 'password'),
            'name' => Yii::t('admin_user', 'name'),
            'encrypt' => Yii::t('admin_user', 'encrypt'),
            'role_id' => Yii::t('admin_user', 'role_id'),
            'disabled' => Yii::t('admin_user', 'disabled'),
            'setting' => Yii::t('admin_user', 'setting'),
            'create_time' => Yii::t('admin_user', 'create_time'),
            'update_time' => Yii::t('admin_user', 'update_time'),
            'role' => Yii::t('admin_user', 'role'),
        );
    }

}