<?php

/**
* This is the model base class for the table "admin_role_priv".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "AdminRolePriv".
*
* Columns in table "admin_role_priv" available as properties of the model,
* and there are no model relations.
*
* @property string $role_id
* @property string $menu_id
*
*/
abstract class BaseAdminRolePriv extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'admin_role_priv';
}

public static function representingColumn() {
return array(
    'role_id',
        'menu_id',
    );
}

public function rules() {
return array(
array('role_id, menu_id', 'required'),
array('role_id, menu_id', 'length', 'max'=>10),
array('role_id, menu_id', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'role_id' => Yii::t('admin_role_priv', 'role_id'),
'menu_id' => Yii::t('admin_role_priv', 'menu_id'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('role_id', $this->role_id, true);
$criteria->compare('menu_id', $this->menu_id, true);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}