<?php

/**
* This is the model base class for the table "action_feed".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "ActionFeed".
*
* Columns in table "action_feed" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property integer $uid
* @property integer $action_type
* @property integer $action_time
* @property string $data
* @property string $subject
*
*/
abstract class BaseActionFeed extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'action_feed';
}

public static function representingColumn() {
return 'data';
}

public function rules() {
return array(
array('uid, data, subject', 'required'),
array('uid, action_type, action_time', 'numerical', 'integerOnly'=>true),
array('subject', 'length', 'max'=>25),
array('action_type, action_time', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, uid, action_type, action_time, data, subject', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('action_feed', 'id'),
'uid' => Yii::t('action_feed', 'uid'),
'action_type' => Yii::t('action_feed', 'action_type'),
'action_time' => Yii::t('action_feed', 'action_time'),
'data' => Yii::t('action_feed', 'data'),
'subject' => Yii::t('action_feed', 'subject'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('uid', $this->uid);
$criteria->compare('action_type', $this->action_type);
$criteria->compare('action_time', $this->action_time);
$criteria->compare('data', $this->data, true);
$criteria->compare('subject', $this->subject, true);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}