<?php

/**
* This is the model base class for the table "user_space_visit_stat".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "UserSpaceVisitStat".
*
* Columns in table "user_space_visit_stat" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property integer $target
* @property string $day
* @property string $times
*
*/
abstract class BaseUserSpaceVisitStat extends GxActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'user_space_visit_stat';
}

public static function representingColumn() {
return 'day';
}

public function rules() {
return array(
array('day', 'required'),
array('target', 'numerical', 'integerOnly'=>true),
array('times', 'length', 'max'=>5),
array('target, times', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, target, day, times', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('user_space_visit_stat', 'id'),
'target' => Yii::t('user_space_visit_stat', 'target'),
'day' => Yii::t('user_space_visit_stat', 'day'),
'times' => Yii::t('user_space_visit_stat', 'times'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('target', $this->target);
$criteria->compare('day', $this->day, true);
$criteria->compare('times', $this->times, true);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}