<?php

/**
* This is the model base class for the table "group_member".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "GroupMember".
*
* Columns in table "group_member" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property integer $group
* @property integer $user
* @property integer $approved
* @property integer $requested
* @property integer $invited
* @property string $requested_date
* @property string $invited_date
* @property string $join_date
* @property integer $inviter
*
*/
abstract class BaseGroupMember extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'group_member';
}

public static function representingColumn() {
return 'requested_date';
}

public function rules() {
return array(
array('group, user, inviter', 'required'),
array('group, user, approved, requested, invited, inviter', 'numerical', 'integerOnly'=>true),
array('requested_date, invited_date, join_date', 'safe'),
array('approved, requested, invited, requested_date, invited_date, join_date', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, group, user, approved, requested, invited, requested_date, invited_date, join_date, inviter', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('group_member', 'id'),
'group' => Yii::t('group_member', 'group'),
'user' => Yii::t('group_member', 'user'),
'approved' => Yii::t('group_member', 'approved'),
'requested' => Yii::t('group_member', 'requested'),
'invited' => Yii::t('group_member', 'invited'),
'requested_date' => Yii::t('group_member', 'requested_date'),
'invited_date' => Yii::t('group_member', 'invited_date'),
'join_date' => Yii::t('group_member', 'join_date'),
'inviter' => Yii::t('group_member', 'inviter'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('group', $this->group);
$criteria->compare('user', $this->user);
$criteria->compare('approved', $this->approved);
$criteria->compare('requested', $this->requested);
$criteria->compare('invited', $this->invited);
$criteria->compare('requested_date', $this->requested_date, true);
$criteria->compare('invited_date', $this->invited_date, true);
$criteria->compare('join_date', $this->join_date, true);
$criteria->compare('inviter', $this->inviter);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}