<?php

/**
* This is the model base class for the table "group_topic_post".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "GroupTopicPost".
*
* Columns in table "group_topic_post" available as properties of the model,
* and there are no model relations.
*
* @property string $id
* @property string $group_id
* @property string $topic_id
* @property string $user_id
* @property string $content
* @property string $ip
* @property integer $create_time
* @property integer $status
* @property integer $is_del
*
*/
abstract class BaseGroupTopicPost extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'group_topic_post';
}

public static function representingColumn() {
return 'content';
}

public function rules() {
return array(
array('group_id, topic_id, user_id, content, ip', 'required'),
array('create_time, status, is_del', 'numerical', 'integerOnly'=>true),
array('group_id, topic_id, user_id', 'length', 'max'=>11),
array('ip', 'length', 'max'=>16),
array('create_time, status, is_del', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, group_id, topic_id, user_id, content, ip, create_time, status, is_del', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('group_topic_post', 'id'),
'group_id' => Yii::t('group_topic_post', 'group_id'),
'topic_id' => Yii::t('group_topic_post', 'topic_id'),
'user_id' => Yii::t('group_topic_post', 'user_id'),
'content' => Yii::t('group_topic_post', 'content'),
'ip' => Yii::t('group_topic_post', 'ip'),
'create_time' => Yii::t('group_topic_post', 'create_time'),
'status' => Yii::t('group_topic_post', 'status'),
'is_del' => Yii::t('group_topic_post', 'is_del'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id, true);
$criteria->compare('group_id', $this->group_id, true);
$criteria->compare('topic_id', $this->topic_id, true);
$criteria->compare('user_id', $this->user_id, true);
$criteria->compare('content', $this->content, true);
$criteria->compare('ip', $this->ip, true);
$criteria->compare('create_time', $this->create_time);
$criteria->compare('status', $this->status);
$criteria->compare('is_del', $this->is_del);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}