<?php

/**
 * This is the model base class for the table "group_topic".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GroupTopic".
 *
 * Columns in table "group_topic" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $creator_id
 * @property integer $created
 * @property integer $active
 * @property integer $group_id
 *
 */
abstract class BaseGroupTopic extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'group_topic';
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('name, creator_id, group_id', 'required'),
            array('creator_id, created, active, group_id', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('created, active', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, creator_id, created, active, group_id', 'safe', 'on' => 'search'),
        );
    }



    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('group_topic', 'id'),
            'name' => Yii::t('group_topic', 'name'),
            'creator_id' => Yii::t('group_topic', 'creator_id'),
            'created' => Yii::t('group_topic', 'created'),
            'active' => Yii::t('group_topic', 'active'),
            'group_id' => Yii::t('group_topic', 'group_id'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('creator_id', $this->creator_id);
        $criteria->compare('created', $this->created);
        $criteria->compare('active', $this->active);
        $criteria->compare('group_id', $this->group_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }


}