<?php

/**
 * This is the model base class for the table "group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Group".
 *
 * Columns in table "group" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $creator
 * @property string $created
 * @property string $type
 * @property integer $active
 *
 */
abstract class BaseGroup extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'group';
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('name, description, creator,  type', 'required'),
            array('creator, active', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('type', 'length', 'max' => 21),
            array('active', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, description, creator, created, type, active', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('group', 'id'),
            'name' => Yii::t('group', 'name'),
            'description' => Yii::t('group', 'description'),
            'creator' => Yii::t('group', 'creator'),
            'created' => Yii::t('group', 'created'),
            'type' => Yii::t('group', 'type'),
            'active' => Yii::t('group', 'active'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('creator', $this->creator);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('type', $this->type, true);
        $criteria->compare('active', $this->active);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}