<?php

/**
* This is the model base class for the table "relationship_type".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "RelationshipType".
*
* Columns in table "relationship_type" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property string $name
* @property string $plural_name
* @property integer $active
* @property integer $mutual
*
*/
abstract class BaseRelationshipType extends YsActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'relationship_type';
}

public static function representingColumn() {
return 'name';
}

public function rules() {
return array(
array('name', 'required'),
array('active, mutual', 'numerical', 'integerOnly'=>true),
array('name, plural_name', 'length', 'max'=>25),
array('plural_name, active, mutual', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, name, plural_name, active, mutual', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('relationship_type', 'id'),
'name' => Yii::t('relationship_type', 'name'),
'plural_name' => Yii::t('relationship_type', 'plural_name'),
'active' => Yii::t('relationship_type', 'active'),
'mutual' => Yii::t('relationship_type', 'mutual'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('name', $this->name, true);
$criteria->compare('plural_name', $this->plural_name, true);
$criteria->compare('active', $this->active);
$criteria->compare('mutual', $this->mutual);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}