<?php

/**
 * This is the model base class for the table "relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Relationship".
 *
 * Columns in table "relationship" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $type
 * @property integer $user_a
 * @property integer $user_b
 * @property integer $accepted
 *
 */
abstract class BaseRelationship extends YsActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'relationship';
    }

    public static function representingColumn()
    {
        return 'id';
    }

    public function rules()
    {
        return array(
            array('type, user_a, user_b', 'required'),
            array('type, user_a, user_b, accepted', 'numerical', 'integerOnly' => true),
            array('accepted', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, type, user_a, user_b, accepted', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('relationship', 'id'),
            'type' => Yii::t('relationship', 'type'),
            'user_a' => Yii::t('relationship', 'user_a'),
            'user_b' => Yii::t('relationship', 'user_b'),
            'accepted' => Yii::t('relationship', 'accepted'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('type', $this->type);
        $criteria->compare('user_a', $this->user_a);
        $criteria->compare('user_b', $this->user_b);
        $criteria->compare('accepted', $this->accepted);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}