<?php

/**
* This is the model base class for the table "blog_recommend".
* DO NOT MODIFY THIS FILE! It is automatically generated by giix.
* If any changes are necessary, you must set or override the required
* property or method in class "BlogRecommend".
*
* Columns in table "blog_recommend" available as properties of the model,
* and there are no model relations.
*
* @property integer $id
* @property integer $user_id
* @property integer $object_id
* @property integer $grade
*
*/
abstract class BaseBlogRecommend extends GxActiveRecord {

public static function model($className=__CLASS__) {
return parent::model($className);
}

public function tableName() {
return 'blog_recommend';
}

public static function representingColumn() {
return 'id';
}

public function rules() {
return array(
array('user_id, object_id', 'required'),
array('user_id, object_id, grade', 'numerical', 'integerOnly'=>true),
array('grade', 'default', 'setOnEmpty' => true, 'value' => null),
array('id, user_id, object_id, grade', 'safe', 'on'=>'search'),
);
}

public function relations() {
return array(
);
}

public function pivotModels() {
return array(
);
}

public function attributeLabels() {
return array(
'id' => Yii::t('blog_recommend', 'id'),
'user_id' => Yii::t('blog_recommend', 'user_id'),
'object_id' => Yii::t('blog_recommend', 'object_id'),
'grade' => Yii::t('blog_recommend', 'grade'),
);
}

public function search() {
$criteria = new CDbCriteria;

$criteria->compare('id', $this->id);
$criteria->compare('user_id', $this->user_id);
$criteria->compare('object_id', $this->object_id);
$criteria->compare('grade', $this->grade);

return new CActiveDataProvider($this, array(
'criteria' => $criteria,
));
}
}