<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => '首页',
  'Setting' => '设置',
  'Site Setting' => '网站设置',
  'Manage' => '管理',
  'Submit' => '提交',
  'Save' => '保存',
  'Create' => '创建',
  'Update' => '更新',
  'Delete' => '删除',
  'Logout' => '退出',
  'Login' => '登录',
  'Register' => '注册',
  //用户
  'Manage Users' => '用户管理',
  'Users' => '用户',
  'Create User' => '创建用户',
  'List User' => '用户列表',
  'Update User' => '更新用户',
  //分类 
  'Manage Categories' => '分类管理',
  'Categories' => '分类',
  'Create Category' => '创建分类',
  'Update Category' => '更新分类',
  //Posts
  'Manage Posts' => '文章管理',
  'Posts' => '文章',
  'Create Post' => '创建文章',
  'Update Post' => '更新文章',
  //标签
  'Manage Tags' => '管理标签',
  'Tags' => '标签',
  'Create Tag' => '创建标签',
  'Update Tag' => '更新标签',
  //评论
  'Manage Comments' => '管理评论',
  'Comments' => '评论',
  'Create Comment' => '创建评论',
  'Update Comment' => '更新评论',
  //链接
  'Manage Links' => '链接管理',
  'Links' => '链接',
  'Create Links' => '创建链接',
  'Update Links' => '更新链接',
  //Attachments
  'Manage Attachments' => '附件管理',
  'Attachments' => '附件',
  'Create Attachments' => '创建附件',
  'Update Attachments' => '更新附件',
    
  //Manage Widgets
  'Manage Widgets' => '扩展管理',  
  //其它
  'Password' => '密码',
  'My Detail' => '我的资料',
  
);
